# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d39278ddf88b8a40122df7df1ffdb805ac5b17091e11f25a2f10fd7b4a0e483ecf34b816afc692ef765d36f876507b06b88289d18696a96372f7725209327e25

test:
  secret_key_base: d5601f6dc4e34524f6d7e9c428418223017fee93f4ca0916e60de8e59c9e756d00b21e4c186c040ea325ca5f4e5eb83cc9b73758a7cd2227a7a5a9710ba7dc53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
